### ISSUE TITLE
When changing vstore preferences for Admin Area general preferences reset to default

### ISSUE THREAD

**Issue by martyshep** [e107inc/vstore#27] opened 2016-11-25 10:17 UTC
Also when viewing vstore/preferences, it does not pull what the current settings are, so when a save made to How to Order or Admin Area tab, General Preferences resets to default.

**Comment by CaMer0n** [comment] 2016-11-29 21:08
@martyshep I'm unable to reproduce this one.  There was an issue with multilan fields which has since been fixed in e107. Maybe you can update e107 from github and try again?

**Comment by martyshep** [comment] 2016-11-29 21:15
Perfect thanks Cameron. I synch'd my e_107 site with git repository and
issue is now cleared.

**Comment by CaMer0n** [comment] 2016-11-29 21:17
cheers!

**Closed** 2016-11-29 21:17 UTC
